<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct();
$customStockStatus = $block->getCustomStockStatus($_product);
?>
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <?php if($customStockStatus): ?>
            <div class="stock success--text available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                <span><?= $customStockStatus ?></span>
            </div>
        <?php else: ?>
            <div class="stock success--text available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
               <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
            </div>
        <?php endif; ?>
    <?php else: ?>
        <?php if($customStockStatus): ?>
            <div class="stock red--text unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                <span><?= $customStockStatus ?></span>
            </div>
        <?php else: ?>
            <div class="stock red--text unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

